# Generated by Django 3.2.13 on 2024-02-23 03:15

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_guest',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(blank=True, help_text='Required. 20 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=20, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='Guest Name'),
        ),
    ]
